### ISSUE TITLE
html tag <masonry> works differently from attribute masonry

### ISSUE THREAD

**Issue by ArniDzhan** [passy/angular-masonry#104]
````html
<masonry column-width="250">
    <div class="masonry-brick" ng-repeat="look in contentData">Unicorns</div>
</masonry>
````
![image](https://cloud.githubusercontent.com/assets/3141905/5738319/a88639e0-9bf3-11e4-9439-1aef62360928.png)

while this works as expected

````html
<div masonry column-width="250">
        <div class="masonry-brick" ng-repeat="look in contentData">Unicorns</div>
    </div>
````
![image](https://cloud.githubusercontent.com/assets/3141905/5738447/fc94c29e-9bf4-11e4-85d7-cf56ec2c02ba.png)

Any ideas?

**Comment by fdev** [comment]
Thanks a bunch for posting this work-around! I could not for the life of me figure out why I kept getting a single column.

**Comment by ArniDzhan** [comment]
> Thanks a bunch for posting this work-around! I could not for the life of me figure out why I kept getting a single column.

most welcome @fdev it seems to be a bug, hopefully will get some idea from contributors on what could be the reason and a possible fix.

**Comment by omer-demir** [comment]
Problem can be caused from browser. Which browser are you using for your output?

**Comment by ArniDzhan** [comment]
> Problem can be caused from browser. Which browser are you using for your output?

FF 35.0.1 and Chrome  40.0.2214.93 m

**Comment by ArniDzhan** [comment]
animations seem to work so it initializes, and here is how debug looks like

![image](https://cloud.githubusercontent.com/assets/3141905/5915339/52e1a244-a60d-11e4-89e7-d9913131a55d.png)

**Comment by ArniDzhan** [comment]
@fdev any ideas?

**Comment by fdev** [comment]
@ArniDzhan Kind of forgot about this issue because the workaround works fine.
However, I just did some debugging and found the reason for this behaviour:

One of the first things Masonry does is getting the size of the container element. I noticed these were different between the `<masonry>` and `<div masonry>` implementations.
The obvious solution for this difference turned out to be the solution to this issue. By adding the following lines to your CSS file the problem disappears:
```css
masonry {
  display: block;
}
```
Please let us know if this indeed fixes the problem, so this issue can be closed.

**Comment by ArniDzhan** [comment]
@fdev thnx for your help, it worked and now we can use <masonry>
